### PR TITLE
Bump riotjs version to 3.0

### PR DESCRIPTION
**Pull request by mradlinski**
Also bumped the version of the package to 4.0.0 - not sure if that's correct and I'll gladly change it, but it seemed to make sense to me.

### CODE REVIEW

**Comment by stukennedy** [comment]
please can we merge this PR?
This is blocking me from upgrading to riot3 in my webpack build as it compiles attributes incorrectly.

**Comment by esnunes** [comment]
It is merged guys, I hope this change does not break anything. As you probably are familiar with I'm not maintaining this project anymore. Let me know if you have interest to maintain it.

**Comment by panganibanpj** [comment]
Looks like Riot created an official loader: https://github.com/riot/tag-loader

**Comment by esnunes** [comment]
nice, @panganibanpj let me know if their version is good enough (I'm confident it is), so I can change the readme file to point to their version.

Thanks!

**Pull request merged**
